// yFiles/demos-js/toolkit/react/src/App.jsx
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML 2.3.0.3.
 ** Copyright (c) 2000-2020 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import React, { Component } from 'react'
import './App.css'
import ReactGraphComponent from './components/ReactGraphComponent.jsx'
import DemoDescription from './components/DemoDescription.jsx'
import yLogo from './assets/ylogo.svg'
import DemoDataPanel from './components/DemoDataPanel.jsx'

export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      graphData: {
        nodesSource: [
          {
            id: 0,
            name: 'Node 0'
          },
          {
            id: 1,
            name: 'Node 1'
          },
          {
            id: 2,
            name: 'Node 2'
          }
        ],
        edgesSource: [
          {
            fromNode: 0,
            toNode: 1
          },
          {
            fromNode: 0,
            toNode: 2
          }
        ]
      }
    }
  }

  addNode() {
    const newIdx =
      this.state.graphData.nodesSource.reduce((maxId, item) => Math.max(maxId, item.id), 0) + 1
    const parentNodeIdx = Math.floor(Math.random() * this.state.graphData.nodesSource.length)
    this.setState(state => {
      const nodesSource = state.graphData.nodesSource.concat({
        id: newIdx,
        name: `Node ${newIdx}`
      })

      // Create an edge if the graph was not empty
      let edgesSource = state.graphData.edgesSource
      if (parentNodeIdx > -1) {
        edgesSource = state.graphData.edgesSource.concat({
          fromNode: nodesSource[parentNodeIdx].id,
          toNode: newIdx
        })
      }

      return {
        graphData: {
          nodesSource,
          edgesSource
        }
      }
    })
  }

  removeNode() {
    this.setState(state => {
      const randomNodeIdx = Math.floor(Math.random() * this.state.graphData.nodesSource.length)
      const newNodesSource = [...state.graphData.nodesSource]
      newNodesSource.splice(randomNodeIdx, 1)

      const nodeId = this.state.graphData.nodesSource[randomNodeIdx].id
      const newEdgesSource = state.graphData.edgesSource.filter(
        edge => edge.fromNode !== nodeId && edge.toNode !== nodeId
      )
      return {
        graphData: {
          nodesSource: newNodesSource,
          edgesSource: newEdgesSource
        }
      }
    })
  }

  resetData() {
    this.setState({
      graphData: {
        nodesSource: [
          {
            id: 0,
            name: 'Node 0'
          },
          {
            id: 1,
            name: 'Node 1'
          },
          {
            id: 2,
            name: 'Node 2'
          }
        ],
        edgesSource: [
          {
            fromNode: 0,
            toNode: 1
          },
          {
            fromNode: 0,
            toNode: 2
          }
        ]
      }
    })
  }

  render() {
    return (
      <div className="App">
        <aside className="demo-sidebar left">
          <DemoDescription />
        </aside>
        <aside className="demo-sidebar right">
          <DemoDataPanel
            graphData={this.state.graphData}
            onAddNode={() => this.addNode()}
            onRemoveNode={() => this.removeNode()}
          />
        </aside>

        <div className="demo-content">
          <div className="demo-header">
            <a href="https://www.yworks.com" target="_blank" rel="noopener noreferrer">
              {' '}
              <img src={yLogo} className="demo-y-logo" alt="yWorks Logo" />{' '}
            </a>{' '}
            <a href="../../../README.html" target="_blank">
              yFiles for HTML
            </a>{' '}
            <span className="demo-title">React Demo [yFiles for HTML]</span>
          </div>

          <ReactGraphComponent
            graphData={this.state.graphData}
            onResetData={() => this.resetData()}
          />
        </div>
      </div>
    )
  }
}

// yFiles/demos-ts/toolkit/angular/src/app/app.component.ts
/****************************************************************************
 ** @license
 ** This demo file is part of yFiles for HTML 2.3.0.3.
 ** Copyright (c) 2000-2020 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ** yFiles demo files exhibit yFiles for HTML functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 **
 ** Owners of a valid software license for a yFiles for HTML version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles for HTML powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles for HTML
 ** license agreement.
 **
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 ***************************************************************************/
import {
  AfterViewInit,
  ApplicationRef,
  Component,
  ComponentFactoryResolver,
  Injector,
  NgZone,
  ViewChild
} from '@angular/core'
import {
  IArrow,
  ICommand,
  IGraph,
  PolylineEdgeStyle,
  OrganicEdgeRouter,
  Size,
  TreeLayout,
  TreeReductionStage,
  INode
} from 'yfiles'
import { GraphComponentComponent } from './graph-component/graph-component.component'
import { EDGE_DATA, NODE_DATA } from './data'
import 'yfiles/view-layout-bridge.js'
import { Person } from './person'
import { NodeComponentStyle } from './NodeComponentStyle'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {
  title = 'app'

  @ViewChild(GraphComponentComponent)
  private gcComponent!: GraphComponentComponent

  public currentPerson?: Person

  // eslint-disable-next-line no-useless-constructor
  constructor(
    private _injector: Injector,
    private _resolver: ComponentFactoryResolver,
    private _appRef: ApplicationRef,
    private _zone: NgZone
  ) {}

  ngAfterViewInit() {
    // run outside Angular so the change detection won't slow down yFiles
    this._zone.runOutsideAngular(() => {
      const graphComponent = this.gcComponent.graphComponent
      const graph = graphComponent.graph

      graph.nodeDefaults.size = new Size(285, 100)
      graph.nodeDefaults.style = new NodeComponentStyle(
        this._injector,
        this._resolver,
        this._appRef,
        this._zone
      )

      graph.edgeDefaults.style = new PolylineEdgeStyle({
        stroke: '2px rgb(170, 170, 170)',
        targetArrow: IArrow.NONE
      })

      graphComponent.addCurrentItemChangedListener(() => {
        this.currentPerson = graphComponent.currentItem!.tag
      })

      createSampleGraph(graph)

      runLayout(graph)

      graphComponent.fitGraphBounds()
    })
  }

  zoomIn() {
    this._zone.runOutsideAngular(() => {
      ICommand.INCREASE_ZOOM.execute(null, this.gcComponent.graphComponent)
    })
  }

  zoomOriginal() {
    this._zone.runOutsideAngular(() => {
      ICommand.ZOOM.execute(1, this.gcComponent.graphComponent)
    })
  }

  zoomOut() {
    this._zone.runOutsideAngular(() => {
      ICommand.DECREASE_ZOOM.execute(null, this.gcComponent.graphComponent)
    })
  }

  fitContent() {
    this._zone.runOutsideAngular(() => {
      ICommand.FIT_GRAPH_BOUNDS.execute(null, this.gcComponent.graphComponent)
    })
  }
}

function createSampleGraph(graph: IGraph): void {
  const nodeMap: { [name: string]: INode } = {}

  NODE_DATA.forEach(nodeData => {
    nodeMap[nodeData.name] = graph.createNode({
      tag: new Person(nodeData)
    })
  })

  EDGE_DATA.forEach(({ from, to }) => {
    const fromNode = nodeMap[from]
    const toNode = nodeMap[to]
    if (fromNode && toNode) {
      graph.createEdge(fromNode, toNode)
    }
  })
}

function runLayout(graph: IGraph): void {
  const treeLayout = new TreeLayout()
  const treeReductionStage = new TreeReductionStage()
  treeReductionStage.nonTreeEdgeRouter = new OrganicEdgeRouter()
  treeReductionStage.nonTreeEdgeSelectionKey = OrganicEdgeRouter.AFFECTED_EDGES_DP_KEY

  treeLayout.appendStage(treeReductionStage)

  graph.applyLayout(treeLayout)
}
